### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by Joshua-Sexton** [davidwarne/dx2vtk#1]
After installing, the system I'm using is failing to recognize "dx2vtk" as a command. What did I do wrong?

**Comment by davidwarne** [comment]
Hi Joshua,

Hope this will help.

Can I confirm that the directory /usr/local/bin is in your PATH environment variable? Also you will need sudo to run the make install step.

Did the binary dx2vtk compile? can you run it from your local directory?

Best,
David

**Comment by Joshua-Sexton** [comment]
Is it possible to use something other than sudo? I am using this on a
university computer system and they do not have that installed I don't
think.

**Comment by Joshua-Sexton** [comment]
Also, "make install" isn't a step listed in the README file for your
program.
And I do not have permission to use the side command on this system.

**Comment by Joshua-Sexton** [comment]
I ran "make install" but had the Makefile install it at a different
directory. It copied the binary and "chmod 755" into the directory I
specified.
What command do I use to use it? I try just "dx2vtk" but it keeps telling
me that isn't a command.

**Comment by Joshua-Sexton** [comment]
I got it to execute, but now it returns the following error:
"dx2vtk: error while loading shared libraries: libioutils.so: cannot open
shared object file: No such file or directory"

**Comment by Joshua-Sexton** [comment]
BTW I appreciate your help with this. If I can get this to run it'll be
very helpful in my research. Also, how do I cite you for this code?
I graduate soon so time is of the essence

**Comment by davidwarne** [comment]
Hi Joshua,

There are a few things to respond to, so bare with me. I will respond in the order you replied

> Is it possible to use something other than sudo? I am using this on a university computer system and they do not have that installed I don't think.

You can compile and run the code without a global install, which if you are running of a university server is what you will need to do. After following the instructions in the README, you should be able to run from the current working directory with ./dx2vtk

> Also, "make install" isn't a step listed in the README file for your program. And I do not have permission to use the side command on this system.

You are correct, but the Makefile does have a simple install option. Your original message said you installed it, so I assume you had attempted this. I should have asked.

> I ran "make install" but had the Makefile install it at a different directory. It copied the binary and "chmod 755" into the directory I specified. What command do I use to use it? I try just "dx2vtk" but it keeps telling me that isn't a command. 

To run  the compiled binary you just need to cd to the repo directory and run with "./dx2vtk" note the leading ./ to specify the currenty directory (if you specify a program name only, then it needs to be in a directory in your PATH variable, this is why it says command not found).

> I got it to execute, but now it returns the following error: "dx2vtk: error while loading shared libraries: libioutils.so: cannot open shared object file: No such file or directory" 

This means step 5) didn't work properly or you have changed directory. 

Can you give me the outputs of the following three commands.

echo $LD_LIBRARY_PATH
echo $PATH
pwd

> BTW I appreciate your help with this. If I can get this to run it'll be very helpful in my research. 

Not a problem, happy to help as best as I can. I hope it is useful. I should warn you that there may be certain types of OpenDX files that this code will not decode, so let me know if you have problems. I developed this code to convert a bunch of old OpenDX files to use the data in ParaView. I followed the OpenDX Specification as best as I could, but I know that some features are not supported.  

> Also, how do I cite you for this code? I graduate soon so time is of the essence

Well there is no academic paper associated with this code. To cite, probably just point to the github page, and a mention in the Acknowledgements of your Thesis would be appreciated.

What is your timeframe for graduation? I am a 3rd year PhD student, so I am also pushing toward my final seminar an Thesis submission, So I will not be able to make any significant updates to the code.

Kind regards,
David

**Comment by Joshua-Sexton** [comment]
Trying run it now produces the following error:
num objects 8
Segmentation fault

**Comment by davidwarne** [comment]
Hi Joshua,

It is impossible to know what is causing the crash without an example data file.

Is it ASCII or Binary data? There is a possible issue if the data header and binary field data are in the same file.

Can you email me a sample file?

Best,
Davis

**Comment by Joshua-Sexton** [comment]
Something like this. Sorry it has taken me so long to respond, I became
quite sick for awhile

**Comment by davidwarne** [comment]
Hi Joshua,
I recently had surgery, so I have also been out of action. I don't see and attachment in your previous comment? Could you send me an example data file?

Is it ASCII data or BINARY? Any ASCII OpenDX file should work fine, but I am aware of issue if the OpenDX header and BINARY data fields are together in the same file.

**Comment by Joshua-Sexton** [comment]
Did they send this time?

**Comment by Joshua-Sexton** [comment]
I sent them as attachments as I tried before

**Comment by davidwarne** [comment]
I still don't see any attachements. 
How large is the file? Have your tried putting in a *.tar.gz  or *.zip file?

**Comment by Joshua-Sexton** [comment]
Ok, how about this zip file? It contains an image of the failure and the
file that I tried to run it on

**Comment by Joshua-Sexton** [comment]
The opendx file is an ASCII file and I want to write a vtk ASCII file.
Executing it prints the number of objects in the dx file, but then results
in a segmentation fault.

**Comment by davidwarne** [comment]
Thanks for the info Joshua.
The issue was a bug in the celldata output function of the VTK file writer (all the files I had written this program for had been pointdata, so this never came up before).

I have just updated the code, check out the new version and let me know how it goes.
